"""Initial migration.

Revision ID: 4abe0f5b4d8d
Revises: 814c58898ea5
Create Date: 2024-08-09 11:24:27.248752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abe0f5b4d8d'
down_revision = '814c58898ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
