"""Update models

Revision ID: 814c58898ea5
Revises: c9545ff363fe
Create Date: 2024-08-04 17:03:44.268014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814c58898ea5'
down_revision = 'c9545ff363fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
